# ==========================================
# AI/ML Internship – Day 35
# Module 7: Introduction to Scikit-learn & First ML Model
# ==========================================

# ==========================================
# Task 1: Theory Answers
# ==========================================

# 1. What is Scikit-learn?
# Answer:
# Scikit-learn is a Python library used for building
# Machine Learning models, data preprocessing,
# training models, and making predictions.

# 2. What is an ML Model?
# Answer:
# A Machine Learning model is a system trained
# using data to learn patterns and make predictions.

# 3. What is a Feature?
# Answer:
# A feature is the input variable used to train
# a Machine Learning model.

# 4. What is a Label?
# Answer:
# A label is the output variable that the model
# tries to predict.

# 5. What is Prediction?
# Answer:
# Prediction is the output generated by a trained
# Machine Learning model based on new input data.


# ==========================================
# Task 2: Dataset Practice
# ==========================================

import pandas as pd

# Student Dataset
student_data = {
    "Hours": [1, 2, 3, 4, 5],
    "Marks": [20, 40, 60, 80, 100]
}

student_df = pd.DataFrame(student_data)

print("Student Dataset")
print(student_df)

# Salary Dataset
salary_data = {
    "Experience": [1, 2, 3, 4, 5],
    "Salary": [25000, 35000, 45000, 55000, 65000]
}

salary_df = pd.DataFrame(salary_data)

print("\nSalary Dataset")
print(salary_df)

# Sales Dataset
sales_data = {
    "Month": [1, 2, 3, 4, 5],
    "Sales": [1000, 2000, 3000, 4000, 5000]
}

sales_df = pd.DataFrame(sales_data)

print("\nSales Dataset")
print(sales_df)


# ==========================================
# Task 3: Model Training
# ==========================================

from sklearn.linear_model import LinearRegression

# Student Model Training
X_student = student_df[["Hours"]]
y_student = student_df["Marks"]

student_model = LinearRegression()

student_model.fit(X_student, y_student)

print("\nStudent Model Trained Successfully")


# ==========================================
# Task 4: Prediction Practice
# ==========================================

# Predict Marks
marks_prediction = student_model.predict([[6]])

print("\nPredicted Marks for 6 Hours:")
print(marks_prediction)

# Salary Prediction
X_salary = salary_df[["Experience"]]
y_salary = salary_df["Salary"]

salary_model = LinearRegression()

salary_model.fit(X_salary, y_salary)

salary_prediction = salary_model.predict([[6]])

print("\nPredicted Salary for 6 Years Experience:")
print(salary_prediction)

# Sales Prediction
X_sales = sales_df[["Month"]]
y_sales = sales_df["Sales"]

sales_model = LinearRegression()

sales_model.fit(X_sales, y_sales)

sales_prediction = sales_model.predict([[6]])

print("\nPredicted Sales for Month 6:")
print(sales_prediction)


# ==========================================
# Task 5: Feature & Label Identification
# ==========================================

# Student Dataset
# Feature (X) = Hours
# Label (y) = Marks

# Salary Dataset
# Feature (X) = Experience
# Label (y) = Salary

# Sales Dataset
# Feature (X) = Month
# Label (y) = Sales

# Explanation of X and y:
# X contains input data (features).
# y contains output data (labels).

# Training Logic:
# The model studies the relationship between X and y.
# After learning the pattern, it predicts outputs
# for new input values.


# ==========================================
# Task 6: Real-World ML Examples
# ==========================================

# 1. House Price Prediction
# Predict house prices using area, location, and rooms.

# 2. Weather Prediction
# Predict temperature and rainfall using historical data.

# 3. Employee Salary Prediction
# Predict salary based on experience and skills.


print("\nDay 35 Tasks Completed Successfully")